import {
  pgTable,
  text,
  timestamp,
  uuid,
  boolean,
  integer,
  jsonb,
  index,
  uniqueIndex,
  check,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { users } from "./auth";

/**
 * Tracks — 8 seeded rows per DEAL-01 (D-01 lookup-table approach).
 *
 * Code values (seeded by plan 04): TE, FL, DP, PO, EC, SL, BL, GI.
 *
 * Ships as a lookup table (not a pgEnum) so Carrie can add/rename tracks
 * during P10 calibration via plain SQL INSERTs — no `ALTER TYPE` migrations.
 */
export const tracks = pgTable(
  "tracks",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    code: text("code").notNull().unique(),
    label: text("label").notNull(),
    defaultPriority: text("default_priority").notNull(),
    active: boolean("active").notNull().default(true),
    sortOrder: integer("sort_order").notNull(),
  },
  (t) => [
    check(
      "tracks_default_priority_check",
      sql`${t.defaultPriority} IN ('HIGH', 'MEDIUM', 'LOW')`,
    ),
  ],
);

/**
 * Stages — seeded per STAGE-01 (D-01 hybrid: track_id NULL = universal).
 *
 * Universal (4): pre_screen_qualification, deal_structuring, file_completed, killed
 * TE (10): title_order_opened ... policy_issued
 * FL (11): deal_team_assigned ... funding_approval_received
 *
 * Track-specific stage lists for DP/PO/EC/SL/BL/GI are deferred to P10
 * calibration (universal stages cover them in P1).
 */
export const stages = pgTable("stages", {
  id: uuid("id").defaultRandom().primaryKey(),
  code: text("code").notNull().unique(),
  label: text("label").notNull(),
  trackId: uuid("track_id").references(() => tracks.id), // NULL = universal
  sortOrder: integer("sort_order").notNull(),
  isTerminal: boolean("is_terminal").notNull().default(false),
});

/**
 * Deals — the core record per DEAL-02.
 *
 * D-03: main_contact as free text in P1 (migrates to contacts FK in P3).
 * D-17: created_by FK users (NOT NULL) — populated from getCurrentUser().
 * D-18: internal_owner FK users (nullable) — defaults to created_by, editable later;
 *       used by "Needs me" filter fallback (D-14).
 * D-19: status text with CHECK (active | closed | killed); P2 adds state machine.
 * file_no auto-generated by next_file_no() — see plan 03.
 */
export const deals = pgTable(
  "deals",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    trackId: uuid("track_id")
      .notNull()
      .references(() => tracks.id),
    stageId: uuid("stage_id")
      .notNull()
      .references(() => stages.id),
    fileNo: text("file_no").notNull().unique(),
    title: text("title").notNull(),
    priority: text("priority").notNull(), // HIGH | MEDIUM | LOW
    status: text("status").notNull().default("active"), // active | closed | killed
    // Main contact free-text per D-03 (migrates to FK in P3)
    mainContactName: text("main_contact_name"),
    mainContactEmail: text("main_contact_email"),
    mainContactPhone: text("main_contact_phone"),
    // Property fields (all nullable per D-09)
    propertyAddress: text("property_address"),
    propertyState: text("property_state"), // 2-letter code (drives file_no prefix)
    propertyType: text("property_type"),
    salesPrice: integer("sales_price"), // whole USD per UI-SPEC (NOT cents)
    // Lending fields
    loanType: text("loan_type"),
    transactionType: text("transaction_type"),
    loanAmount: integer("loan_amount"),
    estimatedDown: integer("estimated_down"),
    earnestMoney: integer("earnest_money"),
    estRehab: integer("est_rehab"),
    arv: integer("arv"),
    titleCtc: boolean("title_ctc").notNull().default(false),
    lenderCtc: boolean("lender_ctc").notNull().default(false),
    // Legacy / misc DEAL-02 fields
    titleFileNo: text("title_file_no"),
    loanNo: text("loan_no"),
    serviceSelected: text("service_selected"),
    quickNote: text("quick_note"),
    // Dates
    openedAt: timestamp("opened_at", { withTimezone: true }).defaultNow().notNull(),
    closingAt: timestamp("closing_at", { withTimezone: true }),
    fundingAt: timestamp("funding_at", { withTimezone: true }),
    closedAt: timestamp("closed_at", { withTimezone: true }),
    // Kill columns per DEAL-06 (P2 plan 01).
    // killedAt is set when status transitions to 'killed'; killReason mirrors
    // the required reason textarea from the kill-deal dialog. Also written as
    // a system note into deal_notes (is_system=true) by plan 05's killDeal action.
    killedAt: timestamp("killed_at", { withTimezone: true }),
    killReason: text("kill_reason"),
    // Ownership per D-17 / D-18
    createdBy: uuid("created_by")
      .notNull()
      .references(() => users.id),
    internalOwner: uuid("internal_owner").references(() => users.id),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    check("deals_priority_check", sql`${t.priority} IN ('HIGH', 'MEDIUM', 'LOW')`),
    check("deals_status_check", sql`${t.status} IN ('active', 'closed', 'killed')`),
    index("deals_file_no_idx").on(t.fileNo),
    index("deals_track_id_idx").on(t.trackId),
    index("deals_stage_id_idx").on(t.stageId),
    index("deals_status_idx").on(t.status),
    index("deals_internal_owner_idx").on(t.internalOwner),
    index("deals_created_at_desc_idx").on(t.createdAt),
  ],
);

/**
 * Audit log (OPS-01) — every mutation writes one row. D-05.
 *
 * P1 writes on deal.create only; P2 extends to update/stage/task mutations.
 * `user_email` is denormalized so GLBA traceability survives user-row deletion.
 * This is Layer 1 of the three-layer audit model (change_history equivalent;
 * see AUDIT.md §1). `npi_access_log` (auth.ts) is Layer 2.
 */
export const auditLog = pgTable(
  "audit_log",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tableName: text("table_name").notNull(), // e.g. "deals"
    recordId: uuid("record_id").notNull(),
    operation: text("operation").notNull(), // create | update | delete
    beforeJson: jsonb("before_json"), // null for create
    afterJson: jsonb("after_json").notNull(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    userEmail: text("user_email").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    check(
      "audit_log_operation_check",
      sql`${t.operation} IN ('create', 'update', 'delete')`,
    ),
    index("audit_log_record_idx").on(t.tableName, t.recordId),
    index("audit_log_user_idx").on(t.userId, t.createdAt),
    index("audit_log_created_at_desc_idx").on(t.createdAt),
  ],
);

/**
 * Tasks (P2 plan 01) — TASK-01..05.
 *
 * Exactly one task per deal may have `is_next = true`; enforced at the DB
 * level by a PARTIAL UNIQUE INDEX `tasks_one_is_next_per_deal_idx` and at
 * the application level by the task server actions (plan 03). The server
 * actions are the happy path — the partial index is the safety net.
 *
 * `advances_stage_to_id` is nullable: when set, completing the task also
 * advances the deal's stage inside the same transaction (TASK-01 auto-
 * advance; plan 03 implements).
 *
 * `parent_task_id` is nullable + self-referential: enables sub-tasks per
 * TASK-01 (UI slot reserved in P2; Carrie can nest tasks in the New Task
 * dialog).
 */
export const tasks = pgTable(
  "tasks",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    dealId: uuid("deal_id")
      .notNull()
      .references(() => deals.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    ownerUserId: uuid("owner_user_id").references(() => users.id),
    dueDate: timestamp("due_date", { withTimezone: true }),
    status: text("status").notNull().default("open"), // open | done | skipped
    isNext: boolean("is_next").notNull().default(false),
    parentTaskId: uuid("parent_task_id").references((): AnyPgColumn => tasks.id, {
      onDelete: "set null",
    }),
    advancesStageToId: uuid("advances_stage_to_id").references(() => stages.id, {
      onDelete: "set null",
    }),
    createdBy: uuid("created_by")
      .notNull()
      .references(() => users.id),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
  },
  (t) => [
    check(
      "tasks_status_check",
      sql`${t.status} IN ('open', 'done', 'skipped')`,
    ),
    index("tasks_deal_id_idx").on(t.dealId),
    index("tasks_owner_user_id_idx").on(t.ownerUserId),
    index("tasks_due_date_idx").on(t.dueDate),
    // PARTIAL UNIQUE INDEX — the is_next invariant enforcement. Drizzle
    // supports this via uniqueIndex(...).where(sql`...`). See migration
    // 0005 for the generated SQL shape.
    uniqueIndex("tasks_one_is_next_per_deal_idx")
      .on(t.dealId)
      .where(sql`${t.isNext} = true`),
  ],
);

/**
 * Deal notes (P2 plan 06) — append-only per UI-SPEC assumption 4.
 *
 * `is_system = true` for notes auto-generated by the app (e.g., the kill
 * reason is mirrored into a system note on kill). User-authored notes
 * always have `is_system = false`.
 *
 * No edit/delete in P2. If Carrie requests edit during calibration, P3
 * adds the affordance.
 */
export const dealNotes = pgTable(
  "deal_notes",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    dealId: uuid("deal_id")
      .notNull()
      .references(() => deals.id, { onDelete: "cascade" }),
    body: text("body").notNull(),
    isSystem: boolean("is_system").notNull().default(false),
    createdBy: uuid("created_by")
      .notNull()
      .references(() => users.id),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (t) => [
    index("deal_notes_deal_id_created_at_idx").on(t.dealId, t.createdAt),
  ],
);

/**
 * Contacts (P3 plan 01) — PEOPLE-01 global registry.
 *
 * Per-deal role assignment lives in {@link dealPeople}; this table is the
 * global roster of every human on any deal. Most columns are nullable so
 * partial records (e.g., "name only" for a just-heard-of lead) are first-
 * class. `email` gets a partial UNIQUE INDEX on `lower(email) WHERE email
 * IS NOT NULL` — autosuggest dedupe without forcing every contact to have
 * a canonical email.
 *
 * `created_by` is NO ACTION (default) — users who authored contact rows
 * should not be deletable while they own data. If P10 ever needs user
 * archival, migrate this FK to SET NULL then.
 */
export const contacts = pgTable(
  "contacts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    fullName: text("full_name").notNull(),
    roleHint: text("role_hint"),
    org: text("org"),
    email: text("email"),
    phone: text("phone"),
    notes: text("notes"),
    createdBy: uuid("created_by")
      .notNull()
      .references(() => users.id),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (t) => [
    // Partial unique — dedupe autosuggest matches by email while allowing
    // many null-email contacts. `lower(email)` collapses casing drift
    // (Gmail addresses round-trip uppercase from paper intake).
    uniqueIndex("contacts_email_unique_idx")
      .on(sql`lower(${t.email})`)
      .where(sql`${t.email} IS NOT NULL`),
    index("contacts_full_name_idx").on(t.fullName),
  ],
);

/**
 * Deal-people link table (P3 plan 01) — PEOPLE-02 role-slot registry.
 *
 * Exactly one row per `(deal_id, role)` — enforced by the UNIQUE INDEX
 * `deal_people_one_per_slot_idx`. That index IS the invariant; it's not a
 * convenience optimization. Server actions (plan 03-04) will layer
 * PEOPLE-05 role-track compatibility on top, but this table is where the
 * one-contact-per-slot guarantee lives at the DB.
 *
 * FK semantics:
 * - `deal_id` CASCADE — a deleted deal takes its slots with it.
 * - `contact_id` SET NULL — deleting a contact never cascade-drops
 *   deal_people rows; it preserves the audit trail ("a contact once
 *   occupied this slot") and leaves `role` as the orphaned marker. A
 *   future server action can backfill a replacement contact.
 * - `created_by` NO ACTION — same reasoning as contacts.
 */
export const dealPeople = pgTable(
  "deal_people",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    dealId: uuid("deal_id")
      .notNull()
      .references(() => deals.id, { onDelete: "cascade" }),
    contactId: uuid("contact_id").references(() => contacts.id, {
      onDelete: "set null",
    }),
    role: text("role").notNull(),
    createdBy: uuid("created_by")
      .notNull()
      .references(() => users.id),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (t) => [
    // PEOPLE-02 invariant: exactly one deal_people row per (deal_id, role).
    uniqueIndex("deal_people_one_per_slot_idx").on(t.dealId, t.role),
    index("deal_people_deal_id_idx").on(t.dealId),
    index("deal_people_contact_id_idx").on(t.contactId),
  ],
);

export type Track = typeof tracks.$inferSelect;
export type NewTrack = typeof tracks.$inferInsert;
export type Stage = typeof stages.$inferSelect;
export type NewStage = typeof stages.$inferInsert;
export type Deal = typeof deals.$inferSelect;
export type NewDeal = typeof deals.$inferInsert;
export type AuditLogRow = typeof auditLog.$inferSelect;
export type NewAuditLogRow = typeof auditLog.$inferInsert;
export type Task = typeof tasks.$inferSelect;
export type NewTask = typeof tasks.$inferInsert;
export type DealNote = typeof dealNotes.$inferSelect;
export type NewDealNote = typeof dealNotes.$inferInsert;
export type Contact = typeof contacts.$inferSelect;
export type NewContact = typeof contacts.$inferInsert;
export type DealPerson = typeof dealPeople.$inferSelect;
export type NewDealPerson = typeof dealPeople.$inferInsert;
